import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, AlertTriangle, ArrowLeft, ArrowRight, BarChart3, BookOpen, Check, CheckCircle2, ChevronRight, ClipboardCheck, Database, FileText, Gauge, LayoutDashboard, MessageSquare, Play, Search, Users, X, Zap } from "lucide-react";
import "./index.css";

type Page = "Overview" | "Action Center" | "Account Health" | "Data Integrity" | "Documents" | "Stakeholders" | "Risks" | "Meetings" | "Playbooks" | "Insights";
type Action = { id:number; title:string; context:string; owner:string; priority:string; due:string; status:string; next:string };

const pages: [Page, any][] = [
  ["Overview", LayoutDashboard], ["Action Center", ClipboardCheck], ["Account Health", Gauge],
  ["Data Integrity", Database], ["Documents", FileText], ["Stakeholders", Users],
  ["Risks", AlertTriangle], ["Meetings", MessageSquare], ["Playbooks", BookOpen], ["Insights", BarChart3]
];

const seed: Action[] = [
  {id:1,title:"Confirm staffing requirement",context:"People Success",owner:"People Success",priority:"High",due:"Today",status:"Waiting",next:"Confirm required engineering capacity."},
  {id:2,title:"Update account plan",context:"Account Operations",owner:"TAM",priority:"Medium",due:"Today",status:"In Progress",next:"Update current priorities and owners."},
  {id:3,title:"Security questionnaire",context:"Documentation",owner:"Client",priority:"High",due:"Tomorrow",status:"Waiting",next:"Follow up for missing controls."},
  {id:4,title:"Invoice confirmation",context:"Finance",owner:"Finance",priority:"Medium",due:"Oct 12",status:"Completed",next:"No action required."},
  {id:5,title:"Validate headcount source",context:"Data Integrity",owner:"TAM",priority:"High",due:"Today",status:"In Progress",next:"Confirm authoritative source."},
  {id:6,title:"QBR agenda review",context:"Client Meeting",owner:"Account Manager",priority:"Medium",due:"Friday",status:"Completed",next:"Share final agenda."}
];

function App(){
  const [page,setPage]=useState<Page>("Overview");
  const [actions,setActions]=useState(seed);
  const [selected,setSelected]=useState<Action|null>(null);
  const [toast,setToast]=useState("");
  const [health,setHealth]=useState(92);
  const [resolved,setResolved]=useState(false);
  const [docSent,setDocSent]=useState(false);
  const [search,setSearch]=useState(false);
  const [query,setQuery]=useState("");
  const [presentation,setPresentation]=useState(false);
  const [step,setStep]=useState(0);

  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
  const createAction=()=>{const a={id:Date.now(),title:"Confirm required engineering capacity",context:"Monthly Account Readout",owner:"People Success",priority:"High",due:"Friday",status:"In Progress",next:"Confirm capacity and hiring timeline."};setActions(x=>[a,...x]);setPage("Action Center");notify("Action created — added to Action Center.")};
  const verify=()=>{if(!selected)return;setActions(x=>x.map(a=>a.id===selected.id?{...a,status:"Verified"}:a));setSelected({...selected,status:"Verified"});notify("Outcome verified — confirm to close.")};
  const close=()=>{if(!selected)return;setActions(x=>x.map(a=>a.id===selected.id?{...a,status:"Completed"}:a));setSelected(null);setHealth(x=>Math.min(99,x+1));notify("Action closed — account state updated.")};
  const runDemo=()=>{setHealth(88);setResolved(false);setPage("Data Integrity");notify("Signal detected — CRM and ERP disagree.");window.setTimeout(()=>{setResolved(true);setHealth(90);notify("Human verification complete — source of truth confirmed.")},1800);window.setTimeout(()=>setPage("Action Center"),3500);window.setTimeout(()=>{setHealth(92);setPage("Overview");notify("Outcome verified — account health restored.")},5600)};
  const filtered=useMemo(()=>actions.filter(a=>(a.title+a.context+a.owner+a.status).toLowerCase().includes(query.toLowerCase())),[actions,query]);
  const presentationPages: Page[]=["Overview","Overview","Data Integrity","Action Center","Meetings","Risks","Insights"];
  const presentationLabels=["Account Overview","What Needs Attention","Data Integrity","Action Center","Meeting → Execution","Risk Radar","Account Pulse Framework"];

  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearch(true)} if(e.key==="Escape"){setSearch(false);setSelected(null);setPresentation(false)} if(e.key.toLowerCase()==="p"&&!e.ctrlKey&&!e.metaKey)setPresentation(x=>!x); if(presentation&&e.key==="ArrowRight")setStep(x=>{const n=Math.min(6,x+1);setPage(presentationPages[n]);return n}); if(presentation&&e.key==="ArrowLeft")setStep(x=>{const n=Math.max(0,x-1);setPage(presentationPages[n]);return n})};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[presentation]);

  return <div className="min-h-screen bg-[#080b10] text-slate-100 flex">
    {!presentation&&<aside className="hidden md:flex w-[238px] shrink-0 h-screen sticky top-0 border-r border-white/10 bg-[#0b0f15] flex-col">
      <div className="p-5 border-b border-white/10"><div className="flex gap-2 items-center"><div className="w-8 h-8 rounded-lg bg-white text-black flex items-center justify-center font-bold">AP</div><div><div className="font-semibold">ACCOUNT PULSE</div><div className="text-[10px] uppercase tracking-[.18em] text-slate-500">Technical Account OS</div></div></div></div>
      <nav className="p-3 space-y-1">{pages.map(([name,Icon])=><button key={name} onClick={()=>setPage(name)} className={"w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm "+(page===name?"bg-white/10 text-white":"text-slate-400 hover:text-white hover:bg-white/5")}><Icon size={16}/>{name}{name==="Action Center"&&<span className="ml-auto text-[10px] px-1.5 py-0.5 rounded bg-amber-400/10 text-amber-300">14</span>}</button>)}</nav>
      <div className="mt-auto p-4"><div className="border border-white/10 rounded-xl p-3"><div className="text-xs text-slate-400">ACME TECHNOLOGIES</div><div className="mt-2 text-sm"><span className="text-emerald-400">●</span> Healthy</div><div className="text-[11px] text-slate-500 mt-1">Demo account · fictional data</div></div></div>
    </aside>}
    <main className="flex-1 min-w-0">
      {!presentation&&<header className="h-16 sticky top-0 z-20 border-b border-white/10 bg-[#090d13]/95 backdrop-blur flex items-center justify-between px-5">
        <button onClick={()=>setSearch(true)} className="w-60 flex items-center gap-2 text-sm text-slate-500 border border-white/10 rounded-lg px-3 py-2"><Search size={15}/>Search <span className="ml-auto text-[10px]">⌘K</span></button>
        <div className="flex items-center gap-2"><span className="hidden lg:block text-[10px] uppercase tracking-wider text-slate-500 border border-white/10 rounded-full px-3 py-1">Demo environment · fictional data</span><button onClick={()=>setPresentation(true)} className="px-3 py-2 text-sm border border-white/10 rounded-lg">Presentation Mode</button><button onClick={runDemo} className="px-3 py-2 text-sm rounded-lg bg-white text-black font-medium flex gap-2 items-center"><Play size={14}/>Run Walkthrough</button></div>
      </header>}
      <div className="max-w-[1400px] mx-auto p-5 lg:p-8">
        {presentation&&<div className="flex justify-between items-center mb-7"><div><div className="text-[10px] uppercase tracking-[.18em] text-slate-500">Account Pulse · Presentation Mode</div><div className="text-xl font-semibold mt-1">{presentationLabels[step]}</div></div><div className="flex gap-2"><button disabled={step===0} onClick={()=>{const n=Math.max(0,step-1);setStep(n);setPage(presentationPages[n])}} className="p-2 border border-white/10 rounded-lg disabled:opacity-30"><ArrowLeft size={16}/></button><button disabled={step===6} onClick={()=>{const n=Math.min(6,step+1);setStep(n);setPage(presentationPages[n])}} className="p-2 border border-white/10 rounded-lg disabled:opacity-30"><ArrowRight size={16}/></button><button onClick={()=>setPresentation(false)} className="p-2 border border-white/10 rounded-lg"><X size={16}/></button></div></div>}
        {page==="Overview"&&<Overview health={health} setPage={setPage} onResolve={()=>notify("Attention item resolved — follow-up remains visible.")}/>}
        {page==="Action Center"&&<ActionCenter actions={actions} setSelected={setSelected}/>}
        {page==="Account Health"&&<Health health={health}/>}
        {page==="Data Integrity"&&<DataIntegrity resolved={resolved} onResolve={()=>{setResolved(true);setHealth(92);notify("Data integrity restored — systems are consistent.")}}/>}
        {page==="Documents"&&<Documents sent={docSent} onSend={()=>{setDocSent(true);notify("Request sent successfully.")}}/>}
        {page==="Stakeholders"&&<Stakeholders/>}
        {page==="Risks"&&<Risks/>}
        {page==="Meetings"&&<Meetings onCreate={createAction}/>}
        {page==="Playbooks"&&<Playbooks/>}
        {page==="Insights"&&<Framework/>}
      </div>
    </main>
    {selected&&<div className="fixed inset-0 z-40 bg-black/60" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full max-w-[460px] bg-[#0c1118] border-l border-white/10 p-6 overflow-auto"><div className="flex justify-between"><div><div className="text-[10px] uppercase tracking-wider text-slate-500">Action detail</div><h2 className="text-xl font-semibold mt-2">{selected.title}</h2></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="grid grid-cols-2 gap-3 mt-7">{[["Owner",selected.owner],["Due",selected.due],["Priority",selected.priority],["Status",selected.status]].map(x=><div key={x[0]} className="border border-white/10 rounded-xl p-3"><div className="text-xs text-slate-500">{x[0]}</div><div className="text-sm mt-1">{x[1]}</div></div>)}</div><div className="mt-6 border border-white/10 rounded-xl p-4"><div className="text-xs uppercase tracking-wider text-slate-500">Definition of Done</div><div className="text-sm text-slate-300 mt-2">Expected outcome confirmed and relevant records updated.</div></div>{selected.status!=="Completed"&&selected.status!=="Verified"&&<button onClick={verify} className="w-full mt-6 py-3 rounded-lg bg-white text-black font-medium">Mark outcome verified</button>}{selected.status==="Verified"&&<button onClick={close} className="w-full mt-6 py-3 rounded-lg bg-emerald-400 text-black font-medium">Confirm & close action</button>}</div></div>}
    {search&&<div className="fixed inset-0 z-50 bg-black/70 flex justify-center pt-[12vh] px-4" onClick={()=>setSearch(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl bg-[#0c1118] border border-white/10 rounded-2xl overflow-hidden"><div className="p-4 border-b border-white/10 flex gap-3"><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actions..." className="bg-transparent outline-none flex-1"/></div><div className="p-2">{filtered.map(a=><button key={a.id} onClick={()=>{setSearch(false);setPage("Action Center");setSelected(a)}} className="w-full p-3 rounded-lg text-left hover:bg-white/5"><div className="text-sm">{a.title}</div><div className="text-xs text-slate-500 mt-1">{a.context} · {a.owner}</div></button>)}</div></div></div>}
    {toast&&<div className="fixed bottom-5 right-5 z-[60] px-4 py-3 rounded-xl border border-white/10 bg-[#111821] flex items-center gap-2 text-sm"><CheckCircle2 size={17} className="text-emerald-400"/>{toast}</div>}
  </div>
}

function Title({eyebrow,title,sub}:{eyebrow:string;title:string;sub:string}){return <div className="mb-7"><div className="text-[10px] uppercase tracking-[.18em] text-slate-500">{eyebrow}</div><h1 className="text-3xl font-semibold tracking-tight mt-1">{title}</h1><p className="text-sm text-slate-400 mt-2">{sub}</p></div>}
function Card({children,className=""}:{children:any;className?:string}){return <div className={"border border-white/10 bg-[#0c1118] rounded-2xl "+className}>{children}</div>}

function Overview({health,setPage,onResolve}:{health:number;setPage:(p:Page)=>void;onResolve:()=>void}){const metrics=[["Delivery","94"],["People","88"],["Documentation","96"],["Data Quality","98"],["Client Engagement","91"]];return <><Title eyebrow="Acme Technologies · Account Operations" title="Account overview" sub="A single operational view of delivery, people, documentation, data quality and client engagement."/><div className="grid lg:grid-cols-[1.2fr_.8fr] gap-4"><Card className="p-6"><div className="flex justify-between"><div><div className="text-sm text-slate-400">Account health</div><div className="text-6xl font-semibold mt-2">{health}</div><div className="text-sm text-emerald-400 mt-1">Healthy</div></div><Gauge className="text-emerald-400" size={30}/></div><div className="grid grid-cols-2 sm:grid-cols-5 gap-2 mt-7">{metrics.map(([n,v])=><button key={n} onClick={()=>setPage("Account Health")} className="text-left p-3 rounded-xl border border-white/10 hover:bg-white/5"><div className="text-[11px] text-slate-500">{n}</div><div className="text-xl mt-1">{v}</div></button>)}</div></Card><Card className="p-6"><div className="text-sm text-slate-400">Account snapshot</div><div className="text-lg font-medium mt-1">Reliable, with watch signals</div><div className="space-y-3 mt-6 text-sm"><div className="flex justify-between"><span className="text-slate-500">Team</span><b>12 engineers</b></div><div className="flex justify-between"><span className="text-slate-500">Data accuracy</span><b>98%</b></div><div className="flex justify-between"><span className="text-slate-500">Documentation</span><b>96%</b></div><div className="flex justify-between"><span className="text-slate-500">Open actions</span><b>14</b></div></div></Card></div><Card className="p-6 mt-5"><div className="flex justify-between items-center"><div><h2 className="text-lg font-medium">What needs my attention?</h2><p className="text-xs text-slate-500 mt-1">Signals surfaced before they become account problems.</p></div><span className="text-[10px] px-2 py-1 rounded-full bg-amber-400/10 text-amber-300">3 watch signals</span></div><div className="grid lg:grid-cols-3 gap-3 mt-5">{[["Staffing confirmation overdue","People Success","Resolve"],["CRM / ERP headcount mismatch","Data Integrity","Investigate"],["Security questionnaire awaiting client response","Documentation","Follow up"]].map((x,i)=><div key={x[0]} className="p-4 rounded-xl border border-white/10"><div className="text-[10px] uppercase tracking-wider text-slate-500">{x[1]}</div><div className="font-medium text-sm mt-3">{x[0]}</div><button onClick={()=>i===0?onResolve():setPage(i===1?"Data Integrity":"Documents")} className="mt-4 text-xs px-3 py-1.5 rounded-md bg-white text-black">{x[2]}</button></div>)}</div></Card></>}

function ActionCenter({actions,setSelected}:{actions:Action[];setSelected:(a:Action)=>void}){return <><Title eyebrow="Execution" title="Action Center" sub="Every commitment has an owner, deadline and next step."/><div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-5">{[["32","Total"],["18","Completed"],["8","In Progress"],["4","Waiting"],["2","Overdue"]].map(x=><Card key={x[1]} className="p-4"><div className="text-2xl font-semibold">{x[0]}</div><div className="text-xs text-slate-500 mt-1">{x[1]}</div></Card>)}</div><Card className="overflow-hidden"><div className="p-4 border-b border-white/10 text-sm font-medium">Every commitment is visible until verified closed.</div><div className="overflow-auto"><table className="w-full text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="text-left p-4">Action</th><th className="text-left p-4">Owner</th><th className="text-left p-4">Priority</th><th className="text-left p-4">Due</th><th className="text-left p-4">Status</th></tr></thead><tbody>{actions.map(a=><tr key={a.id} onClick={()=>setSelected(a)} className="border-t border-white/6 hover:bg-white/5 cursor-pointer"><td className="p-4">{a.title}<div className="text-[11px] text-slate-500 mt-1">{a.context}</div></td><td className="p-4">{a.owner}</td><td className="p-4">{a.priority}</td><td className="p-4 text-slate-400">{a.due}</td><td className="p-4"><span className="px-2 py-1 rounded-full text-[10px] bg-white/8">{a.status}</span></td></tr>)}</tbody></table></div></Card></>}

function Health({health}:{health:number}){return <><Title eyebrow="Explainability" title="Account Health" sub="The score is useful only when the drivers are visible."/><div className="grid lg:grid-cols-[.7fr_1.3fr] gap-4"><Card className="p-8 flex flex-col items-center justify-center min-h-[380px]"><div className="text-xs text-slate-500 uppercase tracking-widest">Current health</div><div className="text-8xl font-semibold mt-4">{health}</div><div className="text-emerald-400">Healthy</div></Card><Card className="p-6"><h2 className="text-lg font-medium">Why is the account at {health}?</h2>{[["Delivery","+18"],["Data Quality","+20"],["Documentation","+19"],["People","+16"],["Client Engagement","+19"]].map(x=><div key={x[0]} className="mt-5"><div className="flex justify-between text-sm"><span>{x[0]}</span><span className="text-slate-400">{x[1]}</span></div><div className="h-2 bg-white/6 rounded mt-2"><div className="h-full bg-slate-300 rounded" style={{width:Math.min(96,parseInt(x[1].slice(1))*5)+"%"}}/></div></div>)}<div className="grid sm:grid-cols-2 gap-3 mt-7"><div className="p-4 rounded-xl border border-emerald-400/15 text-sm">✓ No critical delivery blockers<br/>✓ High data consistency</div><div className="p-4 rounded-xl border border-amber-400/15 text-sm">⚠ Staffing confirmation pending<br/>⚠ One client dependency overdue</div></div></Card></div></>}

function DataIntegrity({resolved,onResolve}:{resolved:boolean;onResolve:()=>void}){return <><Title eyebrow="Data quality" title="Data Integrity" sub="One account. One reliable source of truth."/><div className="grid lg:grid-cols-2 gap-4"><Card className="p-7"><div className="grid grid-cols-3 gap-3 items-center"><Source n="CRM" v="42"/><div className="text-center">→</div><Source n="ERP" v={resolved?"42":"40"}/></div><div className="text-center my-4">↓</div><div className="max-w-[230px] mx-auto"><Source n="Internal Account Record" v="42"/></div><div className={"mt-6 p-4 rounded-xl border "+(resolved?"border-emerald-400/20 bg-emerald-400/5":"border-amber-400/20 bg-amber-400/5")}><div className="flex gap-2 items-center font-medium">{resolved?<CheckCircle2 className="text-emerald-400"/>:<AlertTriangle className="text-amber-300"/>}{resolved?"Data integrity restored":"Mismatch detected"}</div><div className="text-xs text-slate-500 mt-1">{resolved?"All records are consistent.":"Detected a 2-person discrepancy."}</div></div>{!resolved&&<button onClick={onResolve} className="w-full mt-5 py-3 rounded-lg bg-white text-black font-medium">Investigate & resolve discrepancy</button>}</Card><Card className="p-7"><div className="font-medium">Automated signal ≠ automated decision</div><div className="text-xs text-slate-500 mt-1">Human verification remains part of the workflow.</div><div className="space-y-5 mt-7">{[["System detects","CRM / ERP mismatch"],["Human verifies","TAM checks context and source of truth"],["Action","Correct record"],["Verified outcome","Systems consistent"]].map((x,i)=><div className="flex gap-3" key={x[0]}><div className="w-7 h-7 rounded-full bg-white text-black flex items-center justify-center text-xs">{i+1}</div><div><div className="text-sm">{x[0]}</div><div className="text-xs text-slate-500 mt-1">{x[1]}</div></div></div>)}</div></Card></div></>}

function Source({n,v}:{n:string;v:string}){return <div className="p-4 rounded-xl border border-white/10 text-center"><div className="text-xs text-slate-500">{n}</div><div className="text-2xl font-semibold mt-2">{v}</div></div>}
function Documents({sent,onSend}:{sent:boolean;onSend:()=>void}){return <><Title eyebrow="Records" title="Documentation" sub="Client paperwork, always complete and current."/><div className="grid md:grid-cols-2 gap-4">{[["Security Questionnaire","96%","Pending client confirmation"],["Vendor Onboarding","100%","Complete"],["Due Diligence","100%","Complete"],["Account Plan","88%","2 fields pending"]].map((x,i)=><Card className="p-5" key={x[0]}><div className="flex justify-between"><div><div className="font-medium">{x[0]}</div><div className="text-xs text-slate-500 mt-1">{x[2]}</div></div><div className="text-lg">{x[1]}</div></div><div className="h-1.5 bg-white/6 rounded mt-5"><div className="h-full bg-slate-300 rounded" style={{width:x[1]}}/></div>{i===0&&<button disabled={sent} onClick={onSend} className="mt-5 px-3 py-2 text-xs rounded-lg bg-white text-black disabled:opacity-50">{sent?"Request sent":"Request information"}</button>}</Card>)}</div></>}

function Meetings({onCreate}:{onCreate:()=>void}){return <><Title eyebrow="Client communication" title="From conversation to closure" sub="A meeting should produce accountable execution, not just meeting notes."/><Card className="p-6"><div className="grid md:grid-cols-7 gap-2">{["Client Meeting","Decision","Action","Owner","Deadline","Verification","Closure"].map((x,i)=><div key={x} className="p-3 rounded-xl border border-white/10 text-center text-xs">{i+1}. {x}</div>)}</div><div className="grid lg:grid-cols-2 gap-4 mt-8"><div className="p-5 rounded-xl border border-white/10"><div className="text-xs text-slate-500">MONTHLY ACCOUNT READOUT</div><blockquote className="text-lg leading-7 mt-4">“We may need additional engineering capacity for the next delivery cycle.”</blockquote></div><div className="p-5 rounded-xl border border-white/10"><div className="text-sm">Decision: Review staffing requirement.</div><div className="text-sm mt-3">Action: Confirm engineering capacity.</div><div className="text-sm mt-3">Owner: People Success · Friday</div><button onClick={onCreate} className="w-full mt-6 py-3 bg-white text-black rounded-lg font-medium">Create Action</button></div></div></Card></>}

function Stakeholders(){const s=["Client Engineering Lead","Client Product Manager","Account Manager","Technical Account Manager","People Success","Recruiting","Finance"];return <><Title eyebrow="Relationship context" title="Stakeholder Map" sub="Make responsibility and dependencies visible across the account."/><div className="grid md:grid-cols-2 gap-4"><Card className="p-7 min-h-[430px] flex items-center justify-center"><div className="text-center"><div className="mx-auto w-24 h-24 rounded-full border border-white/15 flex items-center justify-center"><Users size={30}/></div><div className="font-medium mt-3">Acme Technologies</div><div className="text-xs text-slate-500">12 engineers</div><div className="grid grid-cols-2 gap-3 mt-7">{s.map(x=><div key={x} className="p-3 border border-white/10 rounded-xl text-xs">{x}</div>)}</div></div></Card><Card className="p-6"><div className="font-medium">Stakeholder context</div>{s.map((x,i)=><div key={x} className="mt-3 p-3 border border-white/10 rounded-xl"><div className="text-sm">{x}</div><div className="text-xs text-slate-500 mt-1">{i%2?"Capacity planning":"Delivery priorities"} · {i+1} open actions</div></div>)}</Card></div></>}

function Risks(){const risks=[["Staffing gap","High","Projected requirement exceeds confirmed capacity."],["Data inconsistency","Medium","CRM and ERP headcount mismatch."],["Documentation deadline","Medium","Security questionnaire awaiting client response."],["Invoice dependency","Low","Finance confirmation pending."]];return <><Title eyebrow="Proactive ownership" title="Risk Radar" sub="Identify signals before they become problems."/><div className="grid lg:grid-cols-2 gap-4"><Card className="p-7 min-h-[450px]"><div className="relative h-[370px] border-l border-b border-white/10"><div className="absolute left-1/2 top-0 bottom-0 border-l border-dashed border-white/10"/><div className="absolute left-0 right-0 top-1/2 border-t border-dashed border-white/10"/>{risks.map((r,i)=><div key={r[0]} className="absolute" style={{left:[72,48,65,28][i]+"%",top:[18,40,62,75][i]+"%"}}><div className="w-4 h-4 rounded-full bg-slate-200 ring-8 ring-white/5"/><div className="text-xs text-slate-300 mt-2 whitespace-nowrap">{r[0]}</div></div>)}</div></Card><Card className="p-6"><div className="font-medium">Active signals</div>{risks.map(r=><div key={r[0]} className="mt-4 p-4 border border-white/10 rounded-xl"><div className="flex justify-between"><span>{r[0]}</span><span className="text-xs text-amber-300">{r[1]}</span></div><div className="text-xs text-slate-500 mt-2">{r[2]}</div><div className="text-xs text-slate-400 mt-2">Owner · Account Manager · Monitoring</div></div>)}</Card></div></>}

function Playbooks(){return <><Title eyebrow="Repeatable execution" title="Playbooks" sub="Turn repeated work into repeatable systems."/><div className="grid md:grid-cols-3 gap-4">{["Client Onboarding","Quarterly Business Review","Security Questionnaire","Staffing Change","Invoice Follow-up","Risk Escalation"].map((x,i)=><Card className="p-5" key={x}><BookOpen size={18}/><div className="font-medium mt-5">{x}</div><div className="text-xs text-slate-500 mt-1">{5+i} steps · owner · dependencies · definition of done</div><button className="text-xs mt-5 flex items-center gap-1">Open playbook <ChevronRight size={13}/></button></Card>)}</div></>}

function Framework(){const items=[["SIGNAL","What changed?"],["CONTEXT","Why does it matter?"],["DECISION","What needs to happen?"],["OWNER","Who is responsible?"],["DEADLINE","When?"],["VERIFICATION","How do we know it is done?"],["OUTCOME","What changed?"]];return <><Title eyebrow="Operating model" title="Account Pulse Framework" sub="Turn signals into verified outcomes."/><Card className="p-6 lg:p-10 grid-bg"><div className="grid md:grid-cols-7 gap-3">{items.map((x,i)=><div key={x[0]} className="p-5 min-h-[160px] rounded-2xl border border-white/10 bg-[#0d131b]"><div className="text-[10px] text-slate-500">0{i+1}</div><div className="font-semibold mt-12">{x[0]}</div><div className="text-xs text-slate-500 mt-2">{x[1]}</div></div>)}</div><div className="mt-10"><div className="text-xs uppercase tracking-widest text-slate-500">Core principle</div><div className="text-3xl font-semibold mt-2">Nothing falls through the cracks.</div><div className="text-sm text-slate-400 mt-3 max-w-2xl leading-6">Clear context, visible ownership, timely follow-up and verified closure create reliability around the client relationship.</div></div><div className="text-center text-xs text-slate-600 mt-10">Built as a practical demonstration of how I approach Technical Account Management.</div></Card></>}

createRoot(document.getElementById("root")!).render(<App/>);