import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,AlertTriangle,ArrowLeft,ArrowRight,BarChart3,BookOpen,BriefcaseBusiness,Check,CheckCircle2,ChevronRight,ClipboardCheck,Command,Database,FileCheck2,FileText,Gauge,GitBranch,HelpCircle,LayoutDashboard,MessageSquare,PanelLeftClose,Play,Plus,Search,ShieldCheck,Target,Users,Workflow,X,Zap} from 'lucide-react';
import './index.css';

type Page='Overview'|'Action Center'|'Account Health'|'Data Integrity'|'Documents'|'Stakeholders'|'Risks'|'Meetings'|'Playbooks'|'Insights';
type Action={id:number;title:string;context:string;owner:string;priority:string;due:string;status:string;dependency:string;next:string};
const nav:[Page,React.ElementType][]= [['Overview',LayoutDashboard],['Action Center',ClipboardCheck],['Account Health',Gauge],['Data Integrity',Database],['Documents',FileText],['Stakeholders',Users],['Risks',AlertTriangle],['Meetings',MessageSquare],['Playbooks',BookOpen],['Insights',BarChart3]];
const initialActions:Action[]=[
{id:1,title:'Confirm staffing requirement',context:'People Success',owner:'People Success',priority:'High',due:'Today',status:'Waiting',dependency:'Capacity confirmation',next:'Confirm required engineering capacity.'},
{id:2,title:'Update account plan',context:'Account Operations',owner:'TAM',priority:'Medium',due:'Today',status:'In Progress',dependency:'Quarterly review',next:'Update current priorities and owners.'},
{id:3,title:'Security questionnaire',context:'Documentation',owner:'Client',priority:'High',due:'Tomorrow',status:'Waiting',dependency:'Client confirmation',next:'Follow up for missing controls.'},
{id:4,title:'Invoice confirmation',context:'Finance',owner:'Finance',priority:'Medium',due:'Oct 12',status:'Completed',dependency:'Invoice review',next:'No action required.'},
{id:5,title:'Validate headcount source',context:'Data Integrity',owner:'TAM',priority:'High',due:'Today',status:'In Progress',dependency:'CRM / ERP mismatch',next:'Confirm authoritative source.'},
{id:6,title:'QBR agenda review',context:'Client Meeting',owner:'Account Manager',priority:'Medium',due:'Friday',status:'Completed',dependency:'QBR preparation',next:'Share final agenda.'},
{id:7,title:'Recruiting capacity check',context:'Staffing',owner:'Recruiting',priority:'High',due:'Friday',status:'Waiting',dependency:'Open role',next:'Confirm hiring timeline.'},
];
const metrics=[['Delivery','94','No critical delivery blockers'],['People','88','Staffing confirmation pending'],['Documentation','96','One client confirmation pending'],['Data Quality','98','CRM, ERP and internal records aligned after verification'],['Client Engagement','91','One follow-up due this week']];
function App(){
 const [page,setPage]=useState<Page>('Overview'); const [actions,setActions]=useState(initialActions); const [selected,setSelected]=useState<Action|null>(null); const [toast,setToast]=useState(''); const [presentation,setPresentation]=useState(false); const [demo,setDemo]=useState(false); const [demoStep,setDemoStep]=useState(0); const [searchOpen,setSearchOpen]=useState(false); const [query,setQuery]=useState(''); const [attention,setAttention]=useState(true); const [dataResolved,setDataResolved]=useState(false); const [docRequested,setDocRequested]=useState(false); const [health,setHealth]=useState(92);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2400)};
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true)} if(e.key==='Escape'){setSearchOpen(false);setSelected(null);setPresentation(false)} if(e.key.toLowerCase()==='p'&&!e.metaKey&&!e.ctrlKey){setPresentation(v=>!v)} if(presentation&&e.key==='ArrowRight') nextPresentation(); if(presentation&&e.key==='ArrowLeft') prevPresentation()};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[presentation,page]);
 const completeAction=(a:Action)=>{setActions(xs=>xs.map(x=>x.id===a.id?{...x,status:'Verified'}:x));setSelected({...a,status:'Verified'});notify('Action verified — confirm to close.');};
 const closeAction=()=>{if(!selected)return;setActions(xs=>xs.map(x=>x.id===selected.id?{...x,status:'Completed'}:x));setSelected(null);setHealth(h=>Math.min(99,h+1));notify('Action closed — account state updated.');};
 const createAction=()=>{const a:Action={id:Date.now(),title:'Confirm required engineering capacity',context:'Monthly Account Readout',owner:'People Success',priority:'High',due:'Friday',status:'In Progress',dependency:'Next delivery cycle',next:'Confirm capacity and hiring timeline.'};setActions(x=>[a,...x]);notify('Action created — added to Action Center.');setPage('Action Center');};
 const startDemo=()=>{setDemo(true);setDemoStep(1);setPage('Data Integrity');setDataResolved(false);setHealth(88);setTimeout(()=>{setDataResolved(true);setDemoStep(2);notify('Signal verified — source of truth confirmed.');},2200);setTimeout(()=>{setDemoStep(3);setPage('Action Center');},4200);setTimeout(()=>{setDemoStep(4);setPage('Overview');setHealth(92);},6500);setTimeout(()=>{setDemo(false);setDemoStep(0);},8500)};
 const steps=['Overview','Attention','Data Integrity','Action Center','Meeting → Execution','Risk Radar','Account Pulse Framework'] as const; const [presStep,setPresStep]=useState(0);
 function nextPresentation(){setPresStep(s=>Math.min(steps.length-1,s+1));setPage((['Overview','Overview','Data Integrity','Action Center','Meetings','Risks','Insights'] as Page[])[Math.min(presStep+1,6)]);}
 function prevPresentation(){setPresStep(s=>Math.max(0,s-1));setPage((['Overview','Overview','Data Integrity','Action Center','Meetings','Risks','Insights'] as Page[])[Math.max(presStep-1,0)]);}
 const filtered=useMemo(()=>actions.filter(a=>(a.title+a.context+a.owner+a.status).toLowerCase().includes(query.toLowerCase())),[actions,query]);
 return <div className="min-h-screen bg-[#080b10] text-slate-100 flex">
   {!presentation&&<aside className="w-[236px] shrink-0 border-r border-white/8 bg-[#0b0f15] hidden md:flex flex-col sticky top-0 h-screen">
    <div className="px-5 py-5 border-b border-white/8"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg bg-white text-black flex items-center justify-center font-bold">AP</div><div><div className="font-semibold tracking-tight">ACCOUNT PULSE</div><div className="text-[10px] uppercase tracking-[.18em] text-slate-500">Technical Account OS</div></div></div></div>
    <div className="px-3 py-4 space-y-1">{nav.map(([n,I])=><button key={n} onClick={()=>setPage(n)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm transition ${page===n?'bg-white/8 text-white':'text-slate-400 hover:text-white hover:bg-white/5'}`}><I size={16}/><span>{n}</span>{n==='Action Center'&&<span className="ml-auto text-[10px] px-1.5 py-0.5 rounded bg-amber-400/10 text-amber-300">14</span>}</button>)}</div>
    <div className="mt-auto p-4"><div className="border border-white/8 rounded-xl p-3 bg-white/[.02]"><div className="text-xs text-slate-400">ACME TECHNOLOGIES</div><div className="mt-2 flex items-center gap-2 text-sm"><span className="w-2 h-2 rounded-full bg-emerald-400"/>Healthy</div><div className="mt-1 text-[11px] text-slate-500">Last reviewed · Just now</div></div></div>
   </aside>}
   <main className="flex-1 min-w-0">v className="border border-white/8 rounded-xl p-3 bg-white/[.02]"><div className="text-xs text-slate-400">ACME TECHNOLOGIES</div><div className="mt-2 flex items-center gap-2 text-sm"><span className="w-2 h-2 rounded-full bg-emerald-400"/>Healthy</div><div className="mt-1 text-[11px] text-slate-500">Last reviewed · Just now</div></div></div>
   </aside>}
   <main className="flex-1 min-w-0">
    <header className={`${presentation?'hidden':''}`} h-[64px] border-b border-white/8 bg-[#090d13]/95 backdrop-blur flex items-center justify-between px-5 sticky top-0 z-20"><div className="flex items-center gap-3"><button className="md:hidden p-2 text-slate-400"><PanelLeftClose size={18}/></button><button onClick={()=>setSearchOpen(true)} className="flex items-center gap-2 text-sm text-slate-500 border border-white/8 bg-white/[.02] rounded-lg px-3 py-2 w-[230px]"><Search size={15}/>Search<span className="ml-auto text-[10px] border border-white/10 rounded px-1.5 py-0.5">⌘K</span></button></div><div className="flex items-center gap-2"><span className="hidden sm:inline text-[10px] uppercase tracking-[.15em] text-slate-500 border border-white/8 rounded-full px-2.5 py-1">Demo environment · fictional data</span><button onClick={()=>setPresentation(true)} className="text-sm px-3 py-2 rounded-lg border border-white/10 hover:bg-white/5">Presentation Mode</button><button onClick={startDemo} className="flex items-center gap-2 text-sm px-3 py-2 rounded-lg bg-white text-black font-medium hover:bg-slate-200"><Play size={14}/> Run Walkthrough</button></div></header>
    <div className="max-w-[1400px] mx-auto p-5 lg:p-8">{presentation&&<div className="flex items-center justify-between mb-6"><div><div className="text-xs uppercase tracking-[.18em] text-slate-500">Account Pulse · Presentation Mode</div><div className="text-xl font-semibold mt-1">{steps[presStep]}</div></div><div className="flex gap-2"><button onClick={prevPresentation} disabled={presStep===0} className="p-2.5 border border-white/10 rounded-lg disabled:opacity-30"><ArrowLeft size={16}/></button><button onClick={nextPresentation} disabled={presStep===6} className="p-2.5 border border-white/10 rounded-lg disabled:opacity-30"><ArrowRight size={16}/></button><button onClick={()=>setPresentation(false)} className="p-2.5 border border-white/10 rounded-lg"><X size={16}/></button></div></div>}
      {page==='Overview'&&<Overview health={health} metrics={metrics} attention={attention} setPage={setPage} onResolve={()=>{setAttention(false);notify('Attention item resolved — follow-up remains visible in timeline.')}}/>}
      {page==='Action Center'&&<ActionCenter actions={actions} selected={selected} setSelected={setSelected} completeAction={completeAction} closeAction={closeAction} />}
      {page==='Account Health'&&<Health health={health}/>} {page==='Data Integrity'&&<DataIntegrity resolved={dataResolved} onResolve={()=>{setDataResolved(true);setHealth(92);notify('Data integrity restored — systems are consistent.')}} demoStep={demoStep}/>} {page==='Documents'&&<Documents requested={docRequested} onRequest={()=>{setDocRequested(true);notify('Request sent successfully.')}}/>} {page==='Stakeholders'&&<Stakeholders/>} {page==='Risks'&&<Risks/>} {page==='Meetings'&&<Meetings createAction={createAction}/>} {page==='Playbooks'&&<Playbooks/>} {page==='Insights'&&<Framework/>}
    </div>
   </main>
   {selected&&<div className="fixed inset-0 z-40 bg-black/50" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full max-w-[470px] bg-[#0c1118] border-l border-white/10 p-6 overflow-auto scrollbar"><div className="flex justify-between items-start"><div><div className="text-xs uppercase tracking-wider text-slate-500">Action detail</div><h2 className="text-xl font-semibold mt-2">{selected.title}</h2></div><button onClick={()=>setSelected(null)} className="p-2 rounded-lg hover:bg-white/5"><X size={18}/></button></div><div className="mt-7 grid grid-cols-2 gap-3">{[['Owner',selected.owner],['Due',selected.due],['Priority',selected.priority],['Status',selected.status]].map(([a,b])=><div className="border border-white/8 rounded-xl p-3" key={a}><div className="text-xs text-slate-500">{a}</div><div className="mt-1 text-sm">{b}</div></div>)}</div><div className="mt-6"><div className="text-sm font-medium">Action lifecycle</div><div className="mt-4 space-y-2">{['Created','Assigned','In Progress','Waiting','Verified','Closed'].map((s,i)=><div key={s} className="flex items-center gap-3"><div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] ${(['Completed','Verified'].includes(selected.status)&&i<=5)||(selected.status==='Waiting'&&i<4)||(selected.status==='In Progress'&&i<3)?'bg-emerald-400 text-black':'bg-white/8 text-slate-500'}`}>{i+1}</div><span className="text-sm">{s}</span>{i<5&&<div className="h-4 w-px bg-white/10 absolute ml-3 mt-10"/>}</div>)}</div></div><div className="mt-7 border border-white/8 rounded-xl p-4 bg-white/[.02]"><div className="text-xs uppercase tracking-wider text-slate-500">Definition of Done</div><div className="mt-2 text-sm leading-6 text-slate-300">Expected outcome confirmed and relevant records updated.</div></div><div className="mt-4 text-sm text-slate-400">Next step: <span className="text-slate-200">{selected.next}</span></div>{selected.status!=='Completed'&&selected.status!=='Verified'?<button onClick={()=>completeAction(selected)} className="mt-7 w-full py-3 rounded-lg bg-white text-black font-medium">Mark outcome verified</button>:selected.status==='Verified'?<button onClick={closeAction} className="mt-7 w-full py-3 rounded-lg bg-emerald-400 text-black font-medium">Confirm & close action</button>:null}</div></div>}
   {searchOpen&&<div className="fixed inset-0 z-50 bg-black/60 flex items-start justify-center pt-[13vh] px-4" onClick={()=>setSearchOpen(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl rounded-2xl border border-white/10 bg-[#0c1118] shadow-2xl overflow-hidden"><div className="p-4 border-b border-white/8 flex items-center gap-3"><Search size={18} className="text-slate-500"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actions, documents, stakeholders..." className="bg-transparent outline-none flex-1 text-sm"/><span className="text-xs text-slate-500">ESC</span></div><div className="max-h-[420px] overflow-auto scrollbar p-2">{filtered.map(a=><button key={a.id} onClick={()=>{setSearchOpen(false);setPage('Action Center');setSelected(a)}} className="w-full text-left p-3 rounded-lg hover:bg-white/5 flex justify-between"><div><div className="text-sm">{a.title}</div><div className="text-xs text-slate-500 mt-1">{a.context} · {a.owner}</div></div><ChevronRight size={16} className="text-slate-600"/></button>)}{!filtered.length&&<div className="p-8 text-center text-sm text-slate-500">No matching records.</div>}</div></div></div>}
   {toast&&<div className="fixed bottom-5 right-5 